#!/bin/bash

script_dir_path=$(dirname $0)
if [ ! -d "$script_dir_path/bin" ]; then
	mkdir $script_dir_path/bin
fi
#g++ -O3 -Wall -o $script_dir_path/bin/srcembed main.cpp
clang++-11 -std=c++20 -O3 -Wall -o "$script_dir_path/bin/srcembed" main.cpp
